image: node

variables:
  JEKYLL_ENV: production

#before_script:
#  - apt-get update -qq && apt-get install -y ruby2.0 ruby2.0-dev
  
cache:
  paths:
  - node_modules/

pages:
  stage: deploy
  image: ruby
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev nodejs npm
  - npm install -g gulp
  - npm install
  - gem install jekyll
  - jekyll build
  artifacts:
    paths:
    - _site
  only:
  - master
