# Site settings
title: mx.klb
description: a software developers page
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://mxklb.gitlab.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Max Kalb
user_description: I studied Optoelectronics & Image Processing. I Did two degrees, a Diplom Engineer (Fh) 2006 and a Master of Science 2011. Besides working in the industry as a software developer with image processing based applications and hardware. Mostly I developed C++/Qt desktop applications for hardware devices such as 3D scanners, optical wavefront sensors and analogue film scanners. If you are looking for some one with skills in image, audio, light or signal prosessing, that's what I am ...
user_title: Software Engineer
user_quote: I only craft clean code ;)
user_workload: 40 # Already address time = workload [% per week]
user_available: 24 # unaddress time [hours per week]
user_salery: 60 # Sallery [Euro per hour]
email: mxklb@protonmail.com
skype_username: live:dev_3647
gitlab_username: mxklb

# Google-analytics
google-analytics:
  id: "UA-97173378-1"

exclude: ['package.json', 'src' , 'node_modules']
